apiVersion: apps/v1
kind: Deployment
metadata:
  name: yukimusic-1
  labels:
    app: yukimusic-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yukimusic-1
  template:
    metadata:
      labels:
        app: yukimusic-1
    spec:
      containers:
      - name: yukimusic-1
        image: us-east1-docker.pkg.dev/eden-admin-bot/yuki-repo/yukimusic:v4
        env:
        - name: DISCORD_TOKEN
