apiVersion: v1
kind: Service
metadata:
  name: lavalink-1
spec:
  type: LoadBalancer
  selector:
    app: lavalink-1
  ports:
#  - name: http
#    port: 80
#    targetPort: 8080
  - name: websock
    port: 2333
    targetPort: 2333
